// Generated by gencpp from file kxr_controller/PressureControlActionGoal.msg
// DO NOT EDIT!


#ifndef KXR_CONTROLLER_MESSAGE_PRESSURECONTROLACTIONGOAL_H
#define KXR_CONTROLLER_MESSAGE_PRESSURECONTROLACTIONGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <kxr_controller/PressureControlGoal.h>

namespace kxr_controller
{
template <class ContainerAllocator>
struct PressureControlActionGoal_
{
  typedef PressureControlActionGoal_<ContainerAllocator> Type;

  PressureControlActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  PressureControlActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::kxr_controller::PressureControlGoal_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::kxr_controller::PressureControlActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kxr_controller::PressureControlActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct PressureControlActionGoal_

typedef ::kxr_controller::PressureControlActionGoal_<std::allocator<void> > PressureControlActionGoal;

typedef boost::shared_ptr< ::kxr_controller::PressureControlActionGoal > PressureControlActionGoalPtr;
typedef boost::shared_ptr< ::kxr_controller::PressureControlActionGoal const> PressureControlActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kxr_controller::PressureControlActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kxr_controller::PressureControlActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kxr_controller::PressureControlActionGoal_<ContainerAllocator1> & lhs, const ::kxr_controller::PressureControlActionGoal_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.goal_id == rhs.goal_id &&
    lhs.goal == rhs.goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kxr_controller::PressureControlActionGoal_<ContainerAllocator1> & lhs, const ::kxr_controller::PressureControlActionGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kxr_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::kxr_controller::PressureControlActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kxr_controller::PressureControlActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kxr_controller::PressureControlActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kxr_controller::PressureControlActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kxr_controller::PressureControlActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kxr_controller::PressureControlActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kxr_controller::PressureControlActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7aec6e2d99481e8fc54c7e0715a478ce";
  }

  static const char* value(const ::kxr_controller::PressureControlActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7aec6e2d99481e8fULL;
  static const uint64_t static_value2 = 0xc54c7e0715a478ceULL;
};

template<class ContainerAllocator>
struct DataType< ::kxr_controller::PressureControlActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kxr_controller/PressureControlActionGoal";
  }

  static const char* value(const ::kxr_controller::PressureControlActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kxr_controller::PressureControlActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"PressureControlGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: kxr_controller/PressureControlGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"uint16 board_idx # ICS controller ID (2n or 2n+1)\n"
"\n"
"# Pressure control parameters\n"
"# If trigger_pressure < target_pressure: pressurization mode\n"
"# If trigger_pressure > target_pressure: depressurization mode\n"
"float32 trigger_pressure # Pressure threshold to start valve operation [kPa]\n"
"float32 target_pressure # Desired pressure level for optimal operation [kPa]\n"
"\n"
"# Air release parameters\n"
"# If the value is zero, pressure control is performed based on trigger_pressure and target_pressure\n"
"# If the value is greater than zero, solenoid valves opens for release_duration[s] and the work conducts to the atmosphere\n"
"float32 release_duration # Duration for atmospheric venting [s]\n"
;
  }

  static const char* value(const ::kxr_controller::PressureControlActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kxr_controller::PressureControlActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PressureControlActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kxr_controller::PressureControlActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kxr_controller::PressureControlActionGoal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
    s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::kxr_controller::PressureControlGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KXR_CONTROLLER_MESSAGE_PRESSURECONTROLACTIONGOAL_H
